version: '3.7'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_USER: "stone"
      POSTGRES_PASSWORD: "stone"
      POSTGRES_DB: "stonedb"
    ports:
      - "5432"
    restart: always
    volumes:
      - ./database/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - postgres-compose-network
      
  webapi:
    image: webapi:latest
    depends_on:
      - "postgres-compose"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"     
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge