version: '3.7'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_USER: "stone"
      POSTGRES_PASSWORD: "stone"
      POSTGRES_DB: "stonedb"
    ports:
      - "15432:5432"
    restart: always
    volumes:
      - /c/git/webapi/webapi/database
      - ./database/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    networks:
      - postgres-compose-network
      
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pabloalipio.one@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "stone"
    ports:
      - "16543:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge